---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: npm
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH   

      cd nodejs
      npm install
      npm run build
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: 'undefined'
    type: text
  - name: APP_URL
    value: 'undefined'
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash


      # setup services used by this app
      cf create-service streaming-analytics lite Streaming-Analytics
      cf create-service iotf-service iotf-service-free Internet-of-Things-Platform

      cf push "${CF_APP}"
      export CF_APP_NAME="$CF_APP"
      # View logs
      #cf logs "${CF_APP}" --recent
